language: go
install:
  - go get -d -t
script:
  - go test -v
before_deploy:
  - go get -d ./...
  - go build -o confreaks ./cmd/confreaks/main.go && tar -czf confreaks-$TRAVIS_TAG.linux-amd64.tar.gz confreaks
  - GOOS=darwin go build -o confreaks ./cmd/confreaks/main.go && tar -czf confreaks-$TRAVIS_TAG.darwin-amd64.tar.gz confreaks
  - GOOS=windows go build -o confreaks.exe ./cmd/confreaks/main.go && zip confreaks-$TRAVIS_TAG.windows-amd64.zip confreaks.exe
deploy:
  provider: releases
  api_key:
    secure: sVl6vPGO+XCJfftM/bzNin83BWK0CYoV6ERqt1gO+ORDLL/pkm1KOQu4AqJQlqGSNImINfe6sv4g1EgzaIzik0Ib3//MJqB/onRS4MKdXU6FgFf9Kb+ovH9xp2yc6hXAayrjv6BlTDiW1vX1Dm3o/DUi5neXuacat5HveNZpdPyb8llV16A/LrmqOLDFtxv1vdDzkEQa3gaVTwNBxsy7TvUBBCG69f3hJcdfouCxQPNukHkislbFtog0UVa1JGVG4UL3gS1fy9rROCvp2HA9qghQ6cBZSNL+knS3SMpFhGqz7Nt8IK4KiCczFnesAwg5WX8Cz1z8tOzMU9GHk0V3SqRWwI88LyF0noI5kIJFj/+UNhu3vbqz2pxgyQt49HS+iGW+sIYZJPiW3X/iT7NK2IZgGo+MYaEgdJJIY9gqCiBuRmTZCgXoEmQDdZCeFFulugJJUxHplgi22NM+YpP7f7F2PJlnE5FaFuIARAAg/qXlSINPwDlnL+y53Os22CZqRm3eXMJh6avFysmW5/3RBRpHPLzA3VTj2EBuF3tDQ9zSMkqyvJbjy5kdlHGEDxeFkmlNn8OiEhBB+2KEvTCNarvubMdIW5GUMeMryC6rWbu5DWn5g3cquodZRunAEp0Cu8vgTRCyeLLULLevLVWcX8xZ93LPgTpcCWnNTrlaY2g=
  file:
    - confreaks-$TRAVIS_TAG.linux-amd64.tar.gz
    - confreaks-$TRAVIS_TAG.darwin-amd64.tar.gz
    - confreaks-$TRAVIS_TAG.windows-amd64.zip
  skip_cleanup: true
  on:
    tags: true
